### ISSUE TITLE
npm run build fails to minify.

### ISSUE THREAD

**Issue by Egrodo** [not-an-aardvark/snoowrap#100]
Hi, I'm trying to use Snoowrap with a React app I'm making. When I start my local npm server it runs perfectly, but when attempting to build it for production I get the error 

> Failed to minify the code from this file:                                                                                             
> ./node_modules/snoowrap/dist/helpers.js:151:55  

It then links me to this: http://bit.ly/2tRViJ9 which tells me to use a pre-compiled version. I tried that as well, but when I do it fails to compile citing hundreds of things inside the pre-compiled version.

I'm sure this is an issue with something I'm doing as this is my first time making a Javascript app. Any help would be appreciated!

**Comment by not-an-aardvark** [comment]
Thanks for the report. I'd like to help, but I'm a bit unclear on what that link is recommending I do. This package needs to work in Node as well, so I can't publish the package with ES modules.

Additionally, snoowrap can't be transpiled to ES5 because it uses an array subclass. The [prebuilt file](https://not-an-aardvark.github.io/snoowrap/snoowrap-v1.min.js) is generated using a beta version of uglify.js, so it can parse `class {}` syntax, but it likely won't be parsable by the version of uglify.js that you're using.

If you just want to get something working, my recommendation would be to include the prebuilt file directly on the page with a `<script>` tag, and use the `snoowrap` global from there. This isn't perfect, and I'm open to other solutions, but I'm not sure it will be possible to include snoowrap as part of your regular build process if it relies on the code being transpiled to ES5 syntax.

**Comment by Egrodo** [comment]
@not-an-aardvark Thanks for the reply. I somewhat understand the issue, and am trying to include it in a script tag. Unfortunately that didn't seem to be working either. It would still give 'snoowrap is undefined'. 

I figured it was probably a quirk with create-react-app, so I did some reading. In their [documentation](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#using-global-variables) I actually found I was using <script> the wrong way. I needed to instead use %PUBLIC_URL%, then define snoowrap from window.snoowrap. After fixing that it compiled and ran successfully!

Apologies for opening an irrelevant issue. I'll do some reading and see if there's a better way of doing this, but for my simple project to learn JS and React I'm happy with it :)

Thanks for your expertise and this wonderful project.
