### ISSUE TITLE
Getting the Url / ID of a submitted post via submitLink()

### ISSUE THREAD

**Issue by ronidavelman** [not-an-aardvark/snoowrap#129]
```
redditBot.getSubreddit('test').submitLink({
    title: unescape(data.Source_Title),
    url: unescape(data.Source_Content)
});
```

Is there a way to get the Url / ID of the submitted post?

**Comment by not-an-aardvark** [comment]
Yes, `submitLink` returns a promise that fulfills with the `Submission` object. In the [documentation example](https://not-an-aardvark.github.io/snoowrap/Subreddit.html#submitLink__anchor), the submitted post would have an ID of `4abmsz`.

**Comment by ronidavelman** [comment]
Got it, thanks
```
              redditBot.getSubreddit('test').submitLink({
                title: unescape(data.Source_Title),
                url: unescape(data.Source_Content)
              }).then((result)=>{
                //result.name.split('_')[1]
              });
```

**Comment by efraimbart** [comment]
Interesting that in order to get the id of the submission we have to resort to `name.split` rather than having something built in. My use case is that I'm only requesting `submit` scope, so attempting to run `await subreddit.submitLink(...).id` fails because it tries to load the submission again after submitting it.
