### ISSUE TITLE
Authorizing using implicit grant flow

### ISSUE THREAD

**Issue by danhab99** [not-an-aardvark/snoowrap#136]
I'm trying to develop a reddit app out of NodeJS and I need it to authorize using the [Implicit Grant Flow](https://github.com/reddit-archive/reddit/wiki/OAuth2#authorization-implicit-grant-flow). Is there a way to do it with snoowrap or should I use a different wrapper?

**Comment by not-an-aardvark** [comment]
Hi,

Snoowrap should be able to work with all access tokens, regardless of whether they were obtained with the implicit grant flow or with another method. However, you would need to set up the parts of the flow that interact directly with the user (for example, opening the user's browser to the correct URL so that they can grant access, and retrieving the access token from the redirected URL afterwards). I think wrappers generally don't handle the latter part, since it's application-specific and it would be difficult to create a one-size-fits-all solution.

**Comment by danhab99** [comment]
Response I was looking for

http://www.reddit.com/r/redditdev/comments/85wbo8/-/dw1qv84
