### ISSUE TITLE
throw new errors.NoCredentialsErrors();

### ISSUE THREAD

**Issue by owocean** [not-an-aardvark/snoowrap#163]
lmao ok so im trying to make this reddit bot and im not sure im pretty sure i type `node app.js` in console but that only gives me this
![2018-09-27_15h43_08](https://user-images.githubusercontent.com/43656163/46176261-0a4ee800-c26c-11e8-972e-2d99ee30debe.png)
i would like some help with this. I see that this was updated two months ago but maybe there are some friendly people who can help me. thanks!

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report. What does your code look like?

**Comment by owocean** [comment]
wow that was fast actually heres my entire code 
![2018-09-27_15h46_18](https://user-images.githubusercontent.com/43656163/46176400-8f3a0180-c26c-11e8-8b25-1475afb97b0c.png)

**Comment by not-an-aardvark** [comment]
It looks like you're using `process.env.CLIENT_ID`, which requires `CLIENT_ID` to be an environment variable. Since you don't seem to be providing any environment variables, snoowrap isn't actually getting the client id from anywhere.

Instead of `node app.js`, you could try running the script with:

```bash
CLIENT_ID=put_the_client_id_here CLIENT_SECRET=put_the_client_secret_here REDDIT_USER=put_the_username_here REDDIT_PASS=put_the_password_here node app.js
```

**Comment by owocean** [comment]
![2018-09-27_15h54_58](https://user-images.githubusercontent.com/43656163/46176743-b1804f00-c26d-11e8-8bbc-c9dec1a6c6e7.png)

**Comment by not-an-aardvark** [comment]
You can read about how to set environment variables on Windows [here](http://www.dowdandassociates.com/blog/content/howto-set-an-environment-variable-in-windows-command-line-and-registry/).

I'm going to close this issue since it doesn't seem to be a problem with snoowrap -- for general questions about topics like setting environment variables or `process.env`, I would recommend posting to StackOverflow instead.
