### ISSUE TITLE
Curious about use of proxies.

### ISSUE THREAD

**Issue by AriaFallah** [not-an-aardvark/snoowrap#2]
This is really a question not an issue.

I've been trying to find a use case for proxies, and haven't really been able to justify their usage. Looking through the code, I saw that it had something to do with `get`, but I'm not entirely sure what the purpose of using the proxy is.

Could you let me know how you used the proxy,  and why you couldn't implement the functionality without proxies?

**Comment by not-an-aardvark** [comment]
Sure, I can explain.

Basically, I used Proxies as catch-all getters. Many exposed objects in this project are lazy; their properties aren't known until they're accessed. The process of accessing them is somewhat expensive (it requires HTTP requests and has to adhere to an external ratelimit), so it's not practical to enumerate all of the object's properties on creation.

For example, suppose my API exposes a lazy `Comment` object, representing a reddit comment. I want the user of the API to be able to get a property of the comment (such as the comment's body or author) by simply accessing the `someComment.body` or `someComment.author` properties. When these properties are accessed, a Promise is returned. Behind the scenes, snoowrap makes an HTTP request to reddit's servers, and receives a JSON response representing the comment in question. Then the Promise is fulfilled with the `body` property of that response.

So far, the functionality I've described doesn't actually require Proxies; it would be possible to achieve the same thing with regular getters by doing something like this:

```js
class Comment {
  // ...
  get body () {
    return request.get('https://reddit.com/something').then(parseResponseSomehow)
  }
  get author () {
    return request.get('https://reddit.com/something').then(parseResponseDifferently)
  }
}
```

However, the problem with getters is that they don't work with arbitrary keys; you have to explicitly define all of the accessible properties. Since reddit occasionally adds properties to their JSON responses, it's not a static list, so it wouldn't be feasible to explicitly define all possible getters. I wanted to be able to use a dynamic getter, similar to python's `__getattr__` function. For example, in python you can do this:

```python
class Example():
    def __getattr__(self, attr):
        # This function gets called whenever a property on this object is accessed.
        # It allows custom behavior when any property is accessed, without having to
        # explicitly define getters for specific properties.

        # In this example, the value at any key is simply that key concatenated with the
        # string ' (proxied value)'.
        return attr + ' (proxied value)'

print(Example().blah)
# => 'blah (proxied value)'
```

Until ES6, javascript had no equivalent of `__getattr__` (as far as I can tell, anyway). However, now that Proxies exist, it's possible to do this:

```js
var someObject = {};
var proxiedObject = new Proxy(someObject, {
  get (target, key) {
    return key + ' (proxied value)';
  }
});

proxiedObject.blah
// => 'blah (proxied value)'
```

This is very useful, because it means I can have the behavior I wanted with the `Comment` object from before, by doing some version of the following:

```js
function get_comment (id) {
  var someInitialProperties = {id: id};
  return new Proxy(someObject, {
    get (target, key) {
      return request.get('https://reddit.com/something').then(someFunctionOf(key))
    }
  });
}
```

In the project itself, this happens [here](https://github.com/not-an-aardvark/snoowrap/blob/1ef3162b0a1cbc4b4490fa4fff1339c5a9a4ee0f/src/objects/RedditContent.js#L19). While there are a few edge-cases that get dealt with, it's essentially the same as the example above.

I hope this helps explain how I used Proxies. I'm going to close this issue for now since it's not an issue with the code, but feel free to continue the conversation if you have any more questions.

**Comment by AriaFallah** [comment]
@not-an-aardvark 

Okay awesome! I think I get it, but I need to read through it a few more times. This library along with the promise chaining one are really interesting and well written.
