### ISSUE TITLE
Authorize account without opening authorization page

### ISSUE THREAD

**Issue by Tank-Missile** [not-an-aardvark/snoowrap#239]
Currently, if I want my application to act through an arbitrary user's account, the user must click the Allow button presented on the authorization page. For consistency in my web extension, this is a problem because I want the user to handle everything through the extension's popup page. If I could  embed the authorization page in the popup, I could workaround this issue. However, this is not possible due to restrictions on external content. Is there a way to recreate this page by:

- Retrieving the currently logged in reddit account.
- Retrieving the app name that will be authorized.
- Retrieving the scope descriptions based on requested scopes.
- Retrieving the application icon.
- Creating Allow and Decline buttons.

![Screenshot_20191103_000237](https://user-images.githubusercontent.com/5893370/68080267-22c5f600-fdce-11e9-8d63-e7a7fbbce815.png)

**Comment by SpyTec** [comment]
It's not possible to have OAuth be done through your own application, it needs to redirect to Reddit and then back to the application.

You can make Reddit OAuth appear in a popup if that suits you better, or since it's a WebExtension you can have a page for your application that Reddit can redirect to. E.g. for Firefox: `moz-extension://a36c3185-4c10-4db2-90a6-be2a2d39b7e1/redirect.html`.

**Comment by Tank-Missile** [comment]
I already have it redirecting to an html file that retrieves the code from the query string, but I was hoping to use a more contained approach. Would it be possible to make a request to the authorization page to automatically Allow or Decline authorization of the account? It's essentially a form, and so I'm making the assumption that submitting it can be automated. In other words, load the authorization page in the background, and perform a submit automatically from there. I hope I'm not bordering on off-topic here.

**Comment by SpyTec** [comment]
Don't think that's possible, but I don't know much about WebExtensions

**Comment by not-an-aardvark** [comment]
I wouldn't recommend this approach. Clicking "allow" on the authorization page is supposed to imply that the user has consented to having your app access their data. If the user isn't actually seeing the authorization page from reddit and clicking the button, then they haven't given that permission, so ostensibly you shouldn't be accessing the API through their account in the first place.

From a security perspective, if your extension requests permission to read/modify content on reddit.com when the user installs it, then it probably has the ability to spoof the authorization form request too. But it still might not be a good idea to do this, because a user could be surprised that (e.g.) the oauth app still has permissions even if the browser extension is uninstalled.

**Comment by Tank-Missile** [comment]
In that case, embedding the auth page in the extension popup window is probably the best way to go about this. The problem is, reddit has the x-frame-options: SAMEORIGIN header in place. This prevents embedding the auth page from being embedded in an iframe.

**Comment by not-an-aardvark** [comment]
Yes, you'll have to go to reddit.com in a top-level window.
