### ISSUE TITLE
getLinkFlairTemplates() returns user templates if `linkId` parameter is not provided

### ISSUE THREAD

**Issue by iMrDJAi** [not-an-aardvark/snoowrap#258]
![image](https://user-images.githubusercontent.com/42304709/79872994-693ff900-83de-11ea-951b-090984dece13.png)
I'm not sure if this is a bug or not, but as I know **link flair templates** are used for submissions, and **user flair templates** are used for users.

By the way I was looking for a way to get the posts flairs object from subreddits, and `get_link_flair_templates()` seems to be the only way to do that, but it just gives you the **user flair templates**.

So.. what then?

**Comment by iMrDJAi** [comment]
Update: I had to use a OAuth request for that:

```js
var flairs = await r.oauthRequest({ uri: `r/${config.subreddit}/api/link_flair_v2` })
```

**Comment by SpyTec** [comment]
Sorry, for late response. For `getLinkFlairTemplates()` it needs a submission ID to get the submission flairs, otherwise the API would return the same things. There is a [`is_newlink`](https://www.reddit.com/dev/api#POST_api_flairselector) parameter we could use for when you're creating a new submission, that could solve the issues you mentioned.

I [`link_flair_v2`](https://www.reddit.com/dev/api#GET_api_link_flair_v2) is something we should implement at some point under a different function name as it helps with the new flair templates. Tracked under #255

**Comment by iMrDJAi** [comment]
@SpyTec It seems that Reddit has fixed this issue and now the endpoint returns the link flairs for whatever value you give as `linkId` even if it's invalid.
