### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by ryan4888** [not-an-aardvark/snoowrap#3]
According to the reddit API wiki, this wrapper has browser support. But I don't see any evidence of that here... Here is the page I'm referring to: https://github.com/reddit/reddit/wiki/API-Wrappers. Does snoowrap have browser support?

**Comment by not-an-aardvark** [comment]
I believe snoowrap should work with [browserify](https://www.npmjs.com/package/browserify) without needing to make any modifications to the code. For example, there aren't any methods that demand access to the filesystem. The methods that *can* access the filesystem (such as [upload_header_image](https://not-an-aardvark.github.io/snoowrap/Subreddit.html#upload_header_image__anchor)) all have alternative options so that they can work in a browser environment.

That said, I haven't yet gotten around to figuring out unit tests for browser support, so it's possible that something related to browser support has broken since I last tested it manually.
