### ISSUE TITLE
Documentation issue/question with access tokens?

### ISSUE THREAD

**Issue by cfjedimaster** [not-an-aardvark/snoowrap#30]
Please forgive me if this question is a RTFM, and it may also belong on the reddit-oauth-helper repo. I'm trying to build an app that will make requests to Reddit to search for subreddit names and find the latest posts in a subreddit. I do not need access to a particular user's account. On the Reddit site, I set up a new app and use the web-site type. This gives me a client_id and client_secret. 

In order to use snoowrap, I can either provide a client_id, client_secret, refresh_token OR an access_token. I wasn't sure what the refresh_token should be, and based on the link to reddit-oauth-helper, it seemed like I could use the command line to generate the access_token and use that.

Ok... so I did that - and in the CLI I selected Permanent, and got a token, but the result had an expires_in value.

So my question is - does Reddit not support a permanent token? If not, how would I use snoowrap to handle fetching an access_token on the fly when it needs to?

Hopefully that makes sense, and I apologize if this is not the proper repo.

**Comment by cfjedimaster** [comment]
As just a followup, obviously my intent here is to launch an app and never have to update my setup values.

**Comment by not-an-aardvark** [comment]
Hello, thanks for the question.

An *access token* is a token that's used to directly access the reddit API. Access tokens always expire after 1 hour.

A *refresh token* is a different type of token. It's not used to directly access the API; instead, it's used to generate access tokens. Refresh tokens are permanent and don't expire. So the usual flow with refresh tokens is:

1. Use the refresh token to generate an access token from the API
1. Use that access token to access the API directly
1. After an hour, the access token will have expired. (Repeat step 1)

snoowrap handles this under the hood if you provide a `refresh_token`. So to use snoowrap permanently, you just need to pass it the `refresh_token` that you got from reddit-oauth-helper. You can ignore the access_token that you got from reddit-oauth-helper, since snoowrap will be able to generate new access tokens on its own.

**Comment by cfjedimaster** [comment]
Thank you so much - this is working perfectly for me now.
