### ISSUE TITLE
Handle OAuth2 refresh-token breaking change

### ISSUE THREAD

**Issue by SpyTec** [not-an-aardvark/snoowrap#304]
[Reddit is changing OAuth2 workflow](https://www.reddit.com/r/redditdev/comments/kvzaot/oauth2_api_changes_upcoming/), we need to ensure snoowrap supports this before 2021Q2

**Comment by not-an-aardvark** [comment]
This is probably going to cause some problems with refresh token storage, I hope reddit reconsiders it. (See [this comment on the thread](https://www.reddit.com/r/redditdev/comments/kvzaot/oauth2_api_changes_upcoming/gj2szb7/) for more details.)

**Comment by oakleyaidan21** [comment]
Hi all, 

I've been running into a problem with `snoowrap.fromAuthCode()` since the new workflow was instated, and I'm wondering if it's related to the issues you've pointed out in the reddit thread, or if reddit has changed something else that breaks it. When I try to use `fromAuthCode()` like I've been doing, I receive `API Error: invalid_grant - undefined` instead of the response I'd normally get. I have not changed my code at all since reddit made the changes -- is there something new I need to be doing? Apologies if this has nothing to do with this specific issue.

**Comment by iMrDJAi** [comment]
@not-an-aardvark @SpyTec This is not a thing anymore! GG!

https://www.reddit.com/r/redditdev/comments/olk5e6/followup_oauth2_api_changes_regarding_refresh/
