### ISSUE TITLE
Allow setting user's flair by template ID?

### ISSUE THREAD

**Issue by OmgImAlexis** [not-an-aardvark/snoowrap#308]
Currently I'm needing to use this as I couldn't find any method to change the user's flair based on the `flair_template_id`.

```ts
await client._selectFlair({
    subredditName: 'mysubreddit',
    name: 'OmgImAlexis',
    flair_template_id: '3d7f8042-39be-11eb-910f-0eb386cc13ed'
})
```

**Comment by SpyTec** [comment]
We do not have flair templates v2 fully implemented, you cannot set posts with their flair template id. We're tracking this under #255 

If you wish to implement the [`link_flair_v2`](https://www.reddit.com/dev/api#GET_api_link_flair_v2) go right ahead, otherwise you can make use of [`oauthRequest`](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#oauthRequest__anchor) for your own code in the meantime

**Comment by OmgImAlexis** [comment]
> We do not have flair templates v2 fully implemented, you cannot set posts with their flair template id. We're tracking this under #255
> 
> If you wish to implement the [`link_flair_v2`](https://www.reddit.com/dev/api#GET_api_link_flair_v2) go right ahead, otherwise you can make use of [`oauthRequest`](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#oauthRequest__anchor) for your own code in the meantime

Honestly not sure how I missed that part of the api docs. Thank you. 🙌
