### ISSUE TITLE
fetch_more growing results will take up too much memory

### ISSUE THREAD

**Issue by lf94** [not-an-aardvark/snoowrap#31]
I'm using fetch_more to tally up some statistics, but fetch_more is keeping results I don't need, which causes me to run out of memory. Could we change this behavior to just returning new results?

**Comment by not-an-aardvark** [comment]
Hmm, interesting issue.

The fact that `fetch_more` keeps previous results is actually an intended feature, since it allows people to easily create a long list of results. But I suppose it does cause memory issues if you don't actually need to store everything, and you just want to do something with each result. I suppose I could add an option to `fetch_more` to not store the previous listing.

Out of interest, what sort of data are you gathering that causes the process to run out of memory?

**Comment by lf94** [comment]
Adding an option would be great. I am tallying up feedback from /r/testimonials, which doesn't require me to keep previous results. I don't actually run out of memory but weird things happen after a few iterations.

**Comment by not-an-aardvark** [comment]
May I ask what kind of weird things happen?

**Comment by lf94** [comment]
"Weird things" appeared to be stale results, but that could easily have been my code.

This is all it is:

```
'use strict';
const snoowrap = require('snoowrap');

// Removed credentials for this paste
const r = new snoowrap({
    user_agent: '',
    client_id: '',
    client_secret: '',
    username:'',
    password:''
});

let initial = r.get_subreddit('testimonials').get_new({limit: 50});

function handleStream(p) {
    p.then(l => {
        let scores = interpretScores(l);

        // Since snoowrap returns all previous results, we just tally everything,
        // on every iteration.
        let tally = tallyUp(scores);

        console.log(tally);

        setTimeout(() => {
            handleStream(l.fetch_more({amount: 50}));
        }, 1000);
    });
}

handleStream(initial);

function tallyUp(scores) {
    var tally = {};

    scores.map(s => {
        tally[s.user] = { positive: 0, negative: 0, unknown: 0};

        switch(s.feedback) {
        case 'P':
            tally[s.user].positive += 1;
            break;
        case 'N':
            tally[s.user].negative += 1;
            break;
        default:
            tally[s.user].unknown += 1;
            break;
        }
    });

    return tally;
}

/* Compile these once */
const userSearch = new RegExp('u/[^ ]+');
const feedbackSearch = new RegExp('\[(POS|pos|NEG|neg)\]');

function interpretScores(l) {
    return l.map(s => {
        const feedback = feedbackSearch.exec(s.title);
        const user = userSearch.exec(s.title);

        return {
            feedback: feedback ? feedback[0].toUpperCase() : 'U',
            user: user ? user[0] : 'Bad input'
        };
    });
}
```

**Comment by not-an-aardvark** [comment]
That's actually a quirk of how the reddit API works -- since the contents of the pages can change at the same time as you're paginating through them, you will sometimes get duplicate results.

e.g. Suppose Post X is 99th on the front page, and Post Y is 100th on the front page. snoowrap tries to get the first 200 items from the front page.

1. snoowrap sends a request for the first 100 items. Reddit sends a response including Post X and Post Y.
1. Post Y gets a few upvotes and becomes ahead of Post X on the front page; now Post Y is 99th, and Post X is 100th.
1. snoowrap sends another request for 'the next 100 items after Post Y' (since Post Y was the last item that snoowrap received in the initial request)
1. The first thing in this response will be Post X. This gets appended to the previous list of 100 items, which means that Post X appears twice.

**Comment by lf94** [comment]
Even for get_new() though? I thought they would be listed chronologically when I fetch them like that...

I can see why people directly address reddit bots vs have reddit bots constantly scan subreddits. Thanks for the addition of that option in any case.

**Comment by not-an-aardvark** [comment]
Hmm, I'm not sure why it would be happening with get_new() actually.
