### ISSUE TITLE
You may need an appropriate loader to handle this file type in package.json

### ISSUE THREAD

**Issue by wnqnguo** [not-an-aardvark/snoowrap#38]
![image](https://cloud.githubusercontent.com/assets/6914629/18021836/fa91e6fe-6b9e-11e6-9984-5d86a5b82e8a.png)

I'm adding snoowrap a react app, but having trouble getting it set up. getting an error in package.json

**Comment by not-an-aardvark** [comment]
So I think I know what the issue is: to ensure the `snoowrap.version` property is up-to-date, snoowrap [imports its own package.json file](/not-an-aardvark/snoowrap/blob/0a6481c2bf3fe0e44eed58d06da8616ce69b88b8/src/constants.js#L1). It seems like webpack is trying to parse the JSON file as a JS file, which is causing a syntax error.

I don't know much about webpack, so I'm not sure of the best way to resolve this. Is there a way for snoowrap to indicate that the file should be loaded as JSON? Would using `require()` rather than `import` solve this? (The `import` statement is transpiled to `require` by babel.js anyway, but I think babel has a bit of extra logic as well.)

I suppose the easiest solution would be to just update the `snoowrap.version` constant manually and avoid importing from package.json. Then there could be a unit test to make sure that the value in package.json matches the constant.

**Comment by not-an-aardvark** [comment]
This should be fixed in v1.6.1.
