### ISSUE TITLE
Is there a way to search comments?

### ISSUE THREAD

**Issue by chovy** [not-an-aardvark/snoowrap#44]
It seems like the default search only searches top level posts.

**Comment by not-an-aardvark** [comment]
Thanks for the question.

Unfortunately, there is no way to search comments; that functionality is not exposed by the reddit API.

**Comment by chovy** [comment]
if that's true, how do these bots exist that reply to comments with a specific phrase?

**Comment by not-an-aardvark** [comment]
I think they generally monitor https://reddit.com/r/all/comments, which is a stream of every comment made on reddit.

You can access this in snoowrap with `r.getSubreddit('all').getComments()`, but I think nowadays there are more comments than it's possible to view with that endpoint while staying within the ratelimit.

**Comment by chovy** [comment]
ahh. so they just refresh that list, but the endpoint updates too fast to stay within the rate limit?

that makes sense. I thought there was a socket api somewhere, how are these live subs working?

**Comment by not-an-aardvark** [comment]
Reddit has "live threads" such as [this one](https://www.reddit.com/live/xmvlp8455hl1), where new messages come in through websockets. snoowrap supports these; see the [LiveThread documentation](https://not-an-aardvark.github.io/snoowrap/LiveThread.html).

I think there's also an experimental thing where comments come in through websockets on regular threads, but snoowrap doesn't support that yet since it hasn't been released in the official API.

I'm not aware of any other socket API for comments in general.

**Comment by chovy** [comment]
Alright, bummer. I guess it can be abused but I find most of the value in reddit is buried in the comments. Its a shame we can't search them.
