### ISSUE TITLE
how do I pass some options to the request library?

### ISSUE THREAD

**Issue by chovy** [not-an-aardvark/snoowrap#50]
I notice you're using `request-promise` under the hood. How can I pass some request options?

I'd like to use a proxy server which request supports as an option:

```
request({
   url: '...',
   proxy: 'http://192.168.1.1:8080'
});
```

I'd like to add a few other options as well. Is there anyway to merge in custom `request` options with snoowrap?

**Comment by not-an-aardvark** [comment]
As a workaround, you can use [oauthRequest](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#oauthRequest__anchor) to send a request directly with options that are passed to `request-promise`. You can also configure a default endpoint domain with the [config](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#config__anchor) function (although I'm not sure that's what you're looking for).

At the moment, there's no way to provide custom request options while still using snoowrap's other functions. This is largely because snoowrap also has to work in a browser, and including all of request-promise's API there would make the minified file very large.

**Comment by chovy** [comment]
You include request-promise module as a dependency. It seems like a trivial fix to merge in optional config args when you're using request-promise and ignoring when using xhr.

**Comment by not-an-aardvark** [comment]
I agree, but I think it might be confusing to have an API like that work in Node and unexpectedly break in browsers. That would also prevent snoowrap from ever changing what request library it used under the hood, because it would need to continue supporting library-specific options. Moreover, snoowrap would have to release a new major update in order to upgrade the version of request-promise that is used internally. In my opinion, this would be bad for users of the library in the long term.

I'm not completely opposed to the idea of allowing config options such as proxies, but I'm also not convinced that passing the options directly to request-promise is the best option.

**Comment by chovy** [comment]
I see. there are a few options I can provide a list if you want. but in my opinion its even better to just support but it as an undocumented feature for power users. But yes if you changed the library you would simply have to bump the major version as the api has now changed if you were to use something other than `request`.

I'm happy to use a fork of this. I'll have to dig in to see where I should merge the custom options but its something I definitely need.

**Comment by not-an-aardvark** [comment]
Hmm, I'm not sure I like the idea of supporting it as an 'undocumented feature for power users'. If it's supported, then it would of course require backwards-compatibility, which would pose the same problems as above.

Potential workaround: You could subclass snoowrap and shadow the `oauthRequest` function, which would allow you to implement custom request behavior. All of snoowrap's other functions should work correctly with the shadowed function, provided that it has the same API as the original.

At the moment, the `oauthRequest` function [also does the ratelimiting and error handling](https://github.com/not-an-aardvark/snoowrap/blob/master/src/request_handler.js#L49-L102), which isn't ideal for subclassing since it would have to duplicate that behavior. But I could probably refactor that out and have `oauthRequest` only correspond to the process of actually making a request.

If you do decide to use a fork instead, I would recommend looking [here](https://github.com/not-an-aardvark/snoowrap/blob/a4870c450ea07c623d1f42bd790c9f4ca8d02495/src/request_handler.js#L55) for where the options are passed to request-promise, and [here](https://github.com/not-an-aardvark/snoowrap/blob/a4870c450ea07c623d1f42bd790c9f4ca8d02495/src/create_config.js) and [here](https://github.com/not-an-aardvark/snoowrap/blob/a4870c450ea07c623d1f42bd790c9f4ca8d02495/src/snoowrap.js#L259-L265) for the process of creating/modifying a config.

**Comment by chovy** [comment]
I think you don't understand how semantic versioning works. the whole idea is if you have non-compatible API changes you bump the major version. For enhancements you bump the minor version and for bug fixes you bump the patch.

So 1.2.3 would be 2.0.0 if you broke the api. Simple as that.

**Comment by not-an-aardvark** [comment]
I know how semantic versioning works. But I still want to avoid breaking changes unless they're absolutely necessary, because breaking changes are inconvenient for users. Bumping the major version alerts users about a backwards-incompatible change and prevents existing code from breaking, but it doesn't make breaking changes completely painless for users; they still have to migrate if they want to use new features.

**Comment by chovy** [comment]
I understand. I was just pointing out that's exactly the problem semantic versioning solves. If you are never willing to break your API then we just spin our wheels as far as moving forward. I think  you can maintain a 1.x branch for back porting 2.x features and bug fixes in the event you ever do swap out the library.

Anyway, its totally up to you its your project and you've done an amazing job with it. But for my bot I need to use some advanced request features. If you don't want to roll the custom options into request defaults then I'll just do it on a fork.

**Comment by not-an-aardvark** [comment]
What do you think of the idea of using a snoowrap subclass that shadows `oauthRequest`? I think that is actually a very applicable solution for this case; it would allow you to have custom request behavior while still using the rest of snoowrap's functionality, and the custom request behavior wouldn't have to be part of snoowrap itself?

**Comment by not-an-aardvark** [comment]
More concretely:

```js
const snoowrap = require('snoowrap');

class SnoowrapWithProxy extends snoowrap {
  oauthRequest () {
    // Make a custom request, using a proxy or whatever other config options you want
  }
}

const r = new SnoowrapWithProxy(credentials);

// etc.
```

**Comment by chovy** [comment]
I need *every* http request to go through the proxy. Not just the oAuth. I was hoping you had one request function that everything uses and I could patch to just merge in some custom options.

I was thinking something like this:


	const r = new snoowrap({
	  userAgent: 'put your user-agent string here',
	  clientId: 'put your client id here',
	  clientSecret: 'put your client secret here',
	  refreshToken: 'put your refresh token here',
	  requestOptions: {
	  	proxy: '...',
	  	timeout: 10000,
	  	...
	  }
	});

and then you can just merge in the `requestOptions` properties to the `request.defaults()`

**Comment by not-an-aardvark** [comment]
With a few exceptions, every snoowrap function calls `oauthRequest` internally. I think subclassing would achieve the behavior that you're looking for.

**Comment by chovy** [comment]
I guess I don't quite understand what would go in the body of the `oAuth()` function in your subclasss. The API should be simple and easy to use.

**Comment by not-an-aardvark** [comment]
Here's a simplified example (this might be closer to what a polished API would look like):

```js
// within snoowrap

const rp = require('request-promise');
class snoowrap {
  makeRequest (options) {
    return rp(options);
  }
  // ...other snoowrap functions
}
```

Then it could be subclassed like this:

```js
// your bot, not within snoowrap

const snoowrap = require('snoowrap');
const rp = require('request-promise');

class SnoowrapWithProxy {
  makeRequest (options) {
    return rp.defaults({proxy: 'example.com'})(options);
  }
}

const r = new SnoowrapWithProxy(credentials);

r.getHot().then(console.log) // this would use the custom makeRequest function that you defined
```

With this setup:

* snoowrap wouldn't necessarily have to use request-promise; it could switch to something else later on without breaking anything
* You could configure a proxy or anything else within your shadowed request function, without snoowrap having to explicitly support it (e.g. if the option was specific to your use-case and not a general feature that would be useful for snoowrap).
* You can use all the rest of snoowrap's functionality while still configuring requests however you want.

**Comment by chovy** [comment]
Alright. Then I guess the only question left is what methods do I need to subclass in order to ensure *every* available request goes through my proxy.

**Comment by not-an-aardvark** [comment]
At the moment (1.10.0), you would have to subclass `oauthRequest`, `credentialedClientRequest`, and `unauthenticatedRequest` to ensure this. However, those methods currently contain a lot of unrelated logic, so subclassing them is not easy right now.

I can probably abstract the request logic itself into a `rawRequest` method that all the other functions depend on, which would allow you to only shadow one method in your subclass and avoid having to duplicate the unrelated logic for ratelimiting, etc.

**Comment by chovy** [comment]
Yes, I was hoping you already have a simple function that everything already goes through. I think that is the easiest approach. Having to subclass all these wrapper functions sounds like a bad idea.

**Comment by not-an-aardvark** [comment]
Okay, sounds good. So I'll add a `rawRequest` function that allows for custom request behavior via subclassing.

**Comment by chovy** [comment]
Awesome. Thanks for entertaining the idea. Nothing I've seen comes close to Snoowrap for node. Not even Praw is this good in Python IMO.

**Comment by chovy** [comment]
Is this documented how to implement my own `rawRequest()`?

**Comment by not-an-aardvark** [comment]
Yes, see [here](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#rawRequest__anchor).

**Comment by chovy** [comment]
Hey, so I tried implementing this but proxy does not work.

```
Unhandled rejection RequestError: Error: tunneling socket could not be established, statusCode=502
```

I know my proxy works...and I can make the request manually via the proxy with curl no problem.

**Comment by not-an-aardvark** [comment]
It's hard to figure out what's going on without further info. What happens if you catch the error and use `console.log` on it?

e.g.

```js
r.getHot().catch(console.log);
```

(Note: The object that gets printed out will have a lot of data, possibly including reddit credentials, so be sure to redact those.)

**Comment by chovy** [comment]
@not-an-aardvark 

Nothing really that I could see:

```
{ RequestError: Error: tunneling socket could not be established, statusCode=502
    at new RequestError (/home/user/test/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/home/user/test/node_modules/request-promise/lib/rp.js:56:32)
    at self.callback (/home/user/test/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/user/test/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at ClientRequest.onConnect (/home/user/test/node_modules/tunnel-agent/index.js:167:23)
    at ClientRequest.g (events.js:291:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:393:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
  name: 'RequestError',
  message: 'Error: tunneling socket could not be established, statusCode=502',
  cause:
   { Error: tunneling socket could not be established, statusCode=502
       at ClientRequest.onConnect (/home/user/test/node_modules/tunnel-agent/index.js:165:19)
       at ClientRequest.g (events.js:291:16)
       at emitThree (events.js:116:13)
       at ClientRequest.emit (events.js:194:7)
       at Socket.socketOnData (_http_client.js:393:11)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at TCP.onread (net.js:543:20) code: 'ECONNRESET' },
  error:
   { Error: tunneling socket could not be established, statusCode=502
       at ClientRequest.onConnect (/home/user/test/node_modules/tunnel-agent/index.js:165:19)
       at ClientRequest.g (events.js:291:16)
       at emitThree (events.js:116:13)
       at ClientRequest.emit (events.js:194:7)
       at Socket.socketOnData (_http_client.js:393:11)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at TCP.onread (net.js:543:20) code: 'ECONNRESET' },
  options:
   { json: true,
     auth: { user: 'xxxx', pass: 'xxxx' },
     headers: { 'user-agent': 'Foo 1.0' },
     baseUrl: 'https://www.reddit.com',
     method: 'POST',
     uri: 'api/v1/access_token',
     form:
      { grant_type: 'password',
        username: 'xxxx',
        password: 'xxxxxx' },
     proxy: 'http://104.219.55.207:3128',
     callback: undefined,
     simple: true,
     resolveWithFullResponse: false },
  response: undefined }
```

**Comment by vavramovski** [comment]
Anyone found a workaround, I had the same error.
