### ISSUE TITLE
Global client ID rate limit when posting?

### ISSUE THREAD

**Issue by lauritzsh** [not-an-aardvark/snoowrap#57]
I have been using your API wrapper for creating a simple website where posts can be queued. The application is a "web app" Reddit type of app since it's running on a server only I have access to.

Because of that I expect users to authorize their own account to my web app through OAuth. All of that is working great, snoowrap is working fine here too. Everyone can be authorized.

The problem is that rate limiting seems to be tied to the client ID/secret for whatever reason, not the individual accounts (like normal Reddit or even mobile applications usually works).

That is if `user_A` posted something at 12:00, then `user_B` has to wait 10 minutes before they are allowed to post. If `user_B` has something queued to post at 12:05 they get a rate limit error that they have to wait for X minutes (in this case probably five minutes). The two accounts have nothing to do with each other, only that they are using the same service (mine). In this example both accounts are established accounts with one being five years old, the other two. One has over 2k karma points, the other ~40 or so.  
However since the service is public for anyone to use I can't expect or know what kind of accounts are connected. Hence it is not fair that `million_karma_power_user_A` has to wait 10 minutes just because `zero_karma_new_user_B` posted something minutes before `million_karma_power_user_A`.  
The Reddit app was created by the five year old accounts with over 2k karma points so that account _should_ not be the problem.

I created a post over at [/r/redditdev](http://reddit.com/r/redditdev) but got no meaningful answer to this question.

Do you have any idea what is causing this issue? I assume this is the way that Reddit works and have nothing to do with your wrapper but lack of answers made me create this issue. You might have knowledge of how Reddit works or know why I am getting a global client ID rate limit when submitting links/self posts.

I really don't want to have users type in their username/password. This doesn't seem very secure or at least trustworthy. Then I feel like I would have to open source it just to prove I am not doing anything malicious with their account information. I believe OAuth is the best but this is very limiting for my service. It would scale horribly with even 100 users having queued posts where I have to re-queue every time any post for any user fails.

**Comment by not-an-aardvark** [comment]
I think the issue is that you're using a "web app" type of reddit app, so all the requests are coming from your server. As far as I know, "web app" apps are ratelimited per client ID rather than per user, since all the requests are coming from the same place (so they would be at greater risk of being abused).

To get around the issue, I think you could use an "installed app" instead and offload the code to the client (e.g. use snoowrap in a browser, and have the posts get submitted from the client's machine). I think ratelimits for installed apps are calculated by user account, which allows many people to use a mobile app at once.

**Comment by lauritzsh** [comment]
I suspected the same, just don't really understand the reasoning behind this if true though (not your's but Reddit's).

With the "installed app" approach however that would require each Reddit user to never close the tab, right? I understand this is a way to get past the limitation but unfortunately seems to hurt the user experience of such a scheduling system.

Another thing with "installed app" is that all tokens are only limited to one hour, right? So once it expires the user would have to re-authorize with the service because otherwise I would not be able to post on their behalf?

Hopefully I am missing something with "installed apps" that will make this possible but at the moment "web app" seems to be the most correct choice since I can request permanent tokens (with refresh tokens) instead of being limited to one hour tokens. Just with the unfortunate limitation that rate limiting is global for my app so it is pretty much useless.  
I am not sure if this is possible (hopefully you know because I have trouble finding this information) but otherwise I can just have an automatic script generating new access tokens for each user every hour or so, so that they would always be able to post something automatically.

I think I will try experimenting with an "installed app" meanwhile and see if I can get something automatic working (if this is all within Reddit's own guidelines for acceptable apps. If this is against any rule then it is not worth much).

**Comment by not-an-aardvark** [comment]
> With the "installed app" approach however that would require each Reddit user to never close the tab, right?

It depends. If you only want to make posts when the user is present (e.g. the user can click a button on your site to make a post), then you could store the token as a cookie or in `localStorage`, and the client could use that anytime. On the other hand, if you want to make a post without the user present (e.g. scheduled posts), then that would be harder.

> Another thing with "installed app" is that all tokens are only limited to one hour, right? So once it expires the user would have to re-authorize with the service because otherwise I would not be able to post on their behalf?

No, tokens for installed apps can be refreshed like any other token, so you wouldn't need to keep asking the user every hour.

> I think I will try experimenting with an "installed app" meanwhile and see if I can get something automatic working

If you do decide to do this, I would recommend actually making it "installed" by running it on a browser. Also, you should double-check that the reddit API rules allow for whatever you decide to do. Keep in mind the security implications of using an "installed app" type. (For example, anyone could make a request that looks like it's coming from your app, because there is no client secret.)

---

To be honest, my impression is that this is the intended behavior of the API ratelimit. If you're collecting a bunch of user tokens in a centralized location, and making requests on behalf of a lot of users from your server, then you're acting as a single "client", and so the global ratelimit should apply. On the other hand, if users are using your code to perform actions from their own browser, then it's more accurate to say that each user is acting independently and the tokens are decentralized. So even if all the users happen to be using the same source code from your installed app, it makes more sense for the ratelimit to be on a per-user basis.

**Comment by lauritzsh** [comment]
> On the other hand, if you want to make a post without the user present (e.g. scheduled posts), then that would be harder.

Yeah, that would be my use case.

Played around with the "installed app" approach and can see that I do in fact get a refresh token back. Since client secret for "installed app" can be omitted this was not a problem.

Unfortunately it did not work either and is globally limited too.

What I gather from all of this and reading other posts (I haven't found posts on this exact situation but similar only) is that it might be global for an IP. Not sure if that is the case with "web app" but it seems to be the case with "installed app". Hopefully "web app" too since that means I can use a client secret for extra security.

That would explain why applications are not bothered by global rate limits. So to get this working for multiple users independently of each other would require me to give them a dedicated IP (currently just speculation as I have yet to test this. I could probably easily test this by running the same client ID/secret on two machines with one connected to a hot spot). That should confirm that it is not the client ID getting globally rate limited but the IP.  

I will test this and report back. Hopefully this information might be useful for others.

> Also, you should double-check that the reddit API rules allow for whatever you decide to do. 

I will definitely have to make sure everything is within their rules. Shame deploying an app just to have it closed for some "abuse" reason even if not intentional.

**Comment by lauritzsh** [comment]
Success! It worked. So rather than my client ID being rate limited globally it seems to be the IP-address of the server. I guess that makes sense (at least more).

Thanks for your help and wrapper, my problems seem not to be related to snoowrap at all so I will close this issue.
