### ISSUE TITLE
how to delete all threads in a subreddit?

### ISSUE THREAD

**Issue by chovy** [not-an-aardvark/snoowrap#60]
I cannot find a function to get all threads for a sub.

I need to delete all threads for a subreddit.

**Comment by not-an-aardvark** [comment]
I don't think an API endpoint for "get all threads" exists (since reddit limits the number of threads in a listing), but I suppose you could repeatedly use [getNew](https://not-an-aardvark.github.io/snoowrap/Subreddit.html#getNew__anchor) and [fetchAll](https://not-an-aardvark.github.io/snoowrap/Listing.html#fetchAll__anchor) and delete all the threads that are returned until there are no threads left.

**Comment by chovy** [comment]
can i do something like:

`r.getSubreddit('snoowrap').getNew().delete()`

and just keep doing that?

**Comment by not-an-aardvark** [comment]
That wouldn't work because `getNew()` returns a Promise for a Listing, but you can only delete an individual post.

You could do something like

```js
r.getSubreddit('foo')
  .getNew({ limit: Infinity })
  .map(post => post.delete());
```

(possibly repeating a few times after the script finishes)

Of course, this would only work if your account was the OP of every post on the subreddit (since only the OP can delete a submission).

**Comment by chovy** [comment]
i'm a moderator. can i use `post.remove()` instead?

**Comment by not-an-aardvark** [comment]
Yes.

**Comment by chovy** [comment]
This did the trick! thank you.
