### ISSUE TITLE
listing._more.count not updated on fetchMore?

### ISSUE THREAD

**Issue by ucarion** [not-an-aardvark/snoowrap#61]
I realize it's not documented, but I'm using the `_more.count` property of listings to display how many more comments are not shown. I don't think that property gets updated when you call `fetchMore` on a listing.

**Comment by not-an-aardvark** [comment]
(Obligatory warning against using undocumented properties)

It looks like this is happening due to [this line](https://github.com/not-an-aardvark/snoowrap/blob/6947adadb41707dc9e7b37b140a67acaa7d593f3/src/objects/Listing.js#L196). I *think* you could get around it by using `comment._more.children.length`, but again, this is undocumented, so I wouldn't recommend relying on it.

I guess I could add a `repliesCount` property to comments objects to account for this. However, there is a caveat to this number: after a comment chain reaches a certain depth, reddit stops displaying "load more comments" buttons and displays a "continue this thread" link instead. Snoowrap abstracts this behavior away so that there isn't an inconsistency (i.e. `comment.replies.fetchMore()` works in either case), but it would cause the `repliesCount` number to be inaccurate. (Reddit's API represents a "continue this thread" link by sending a `More` object with ID `t1__` which always has a `count` value of 0, even if the comment actually has replies.)

**Comment by ucarion** [comment]
I just ran into this issue (I observed it as `isFinished` being `false`, but `_more` being null). I'm not sure what the right behavior would be, given that Snoowrap abstracts away the idea of `MoreComments` (if that abstraction weren't there, you could return a `ContinueThisThread` that's similar to a `MoreComments`, but that doesn't seem like an option for Snoowrap).

Would it be safe to add a line copying `count` from the new Listing?

**Comment by not-an-aardvark** [comment]
Closing because this isn't an issue with snoowrap, since `_more` is a private API.
