### ISSUE TITLE
There seems to be no throttling? Exception handling?

### ISSUE THREAD

**Issue by MystK** [not-an-aardvark/snoowrap#74]
A large reason of why I was interested in using snoowrap was because I had assumed that there was built in API throttling, but it doesn't seem to be the case. 

I had assumed that when I called a method, the promise would not resolve until it made all the necessary calls.

If the rate limit was exceeded, I expected the promise to wait until it was able to make more API calls then successfully resolve.

Actual results are that an error is just thrown.

Is there any plans to implement throttling?

This makes me also question what happens when there are Reddit high load issues? If snoowrap does not get a successful 200 status response or there is a timeout, does it just error out, or is there retry functionality built in?

**Comment by not-an-aardvark** [comment]
> A large reason of why I was interested in using snoowrap was because I had assumed that there was built in API throttling, but it doesn't seem to be the case.

> I had assumed that when I called a method, the promise would not resolve until it made all the necessary calls.

You can enable throttling with:

```js
r.config({ requestDelay: 1000 });
```

> If the rate limit was exceeded, I expected the promise to wait until it was able to make more API calls then successfully resolve.

You can enable that behavior with:

```js
r.config({ continueAfterRatelimitError: true });
```

> This makes me also question what happens when there are Reddit high load issues? If snoowrap does not get a successful 200 status response or there is a timeout, does it just error out, or is there retry functionality built in?

By default, snoowrap retries a `GET`, `DELETE`, or `PUT` request up to 3 times if the status code is either 502, 503, 504, or 522. It does not retry other types of requests because this could cause side-effects (e.g. you could accidentally submit a post multiple times depending on where the error occurred).

You can change the retry count using:

```js
r.config({ maxRetryAttempts: 5 });
```

It looks like snoowrap can already do a lot of the things you want -- I would recommend taking a look at the [`snoowrap#config` docs](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#config__anchor).

**Comment by MystK** [comment]
Oh my god... AMAZING! YES. Thank you for pointing these out for me. I had just assumed that these amazing features would have been enabled by default. Thanks and sorry! :)
