### ISSUE TITLE
[Question] getNewComments() fetch only comments within a certain timeframe

### ISSUE THREAD

**Issue by snwflake** [not-an-aardvark/snoowrap#77]
Title should be self-explanatory. 
Currently `getNewComments()` fetches all(?) comments when chaining into `foo.getSubreddit('bar')`. Inspecting the source I found some sort of 'time' param, but couldn't find anything about it in the docs.

**Comment by not-an-aardvark** [comment]
Most of the properties of API objects come directly from the reddit API. You can look at the `created_utc` property to determine when a comment was posted and filter it accordingly.

(Does that answer your question? I'm not sure I understand what you're asking.)

**Comment by snwflake** [comment]
Ya, I noticed the `created_utc` property a minute ago. Even though checking the created_utc property would work, the main question was more like: Is it possible to pass a time parameter to only query for created comments within this timeframe. E.g. `foo.getNewComments({"limit": x, "frame": 60})`, to reduce request time when querying large amounts.

**Comment by not-an-aardvark** [comment]
No, it's not possible to do this because reddit doesn't expose an API like that.

If you're using reddit's search feature for posts, then you can do something like this with [cloudsearch](https://www.reddit.com/r/reddittips/comments/2ix73n/use_cloudsearch_to_search_for_posts_on_reddit/), but reddit doesn't support doing it for comments.

**Comment by snwflake** [comment]
Alright, thanks for your advise and the link, that will be useful in the future too. 
Btw, thanks for snoowrap, appreciate it. 
/close
